# Generated by Django 3.0.3 on 2021-10-24 12:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_classified_status_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='images',
            field=models.ImageField(default='E:\\Django_React\\classifieds_app\\ads\\ads\\2bhk.jpg', upload_to=api.models.upload_to, verbose_name='Images'),
        ),
    ]
