# Generated by Django 3.0.3 on 2021-10-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211024_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='images',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
