# Generated by Django 3.0.3 on 2021-10-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_district_state_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='zip_code',
        ),
    ]
