# Generated by Django 3.0.3 on 2021-10-28 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_district_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classified',
            name='district',
        ),
        migrations.RemoveField(
            model_name='classified',
            name='state',
        ),
        migrations.AddField(
            model_name='classified',
            name='district_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Classified', to='api.District'),
        ),
        migrations.AddField(
            model_name='classified',
            name='state_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Classified', to='api.State'),
        ),
    ]
