# Generated by Django 3.0.3 on 2021-12-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211028_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
