# Generated by Django 3.0.3 on 2021-12-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_classified_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='zip_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
