# Generated by Django 3.0.3 on 2021-12-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211223_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='images',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
