# Generated by Django 3.0.3 on 2022-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211223_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='ads_expire_day',
            field=models.IntegerField(default=0),
        ),
    ]
